MODSOURCE-326
folio-org/mod-source-record-storage pull request #380
Opened 2021-09-16 12:01 UTC by AivarIUsupov

## Purpose
_Incorrect number of totalRecords when calling /source-storage/records?limit=0_

## Approach
_Added validation for limit argument to execute query even if limit equals to zero. That helps to always see the number of totalRecords in the response._

## Learning
_[MODSOURCE-326](https://issues.folio.org/browse/MODSOURCE-326)_

2021-09-16 12:36 UTC, VRohach commented
@AivarIUsupov  Please add some tests for this case.
Moreover, add this ticket to the NEWS.md-file.

2021-09-16 12:38 UTC, VRohach requested changes
@AivarIUsupov Please add some tests for this case.
Moreover, add this ticket to the NEWS.md-file.

2021-09-17 09:53 UTC, Aliaksandr-Fedasiuk approved these changes

2021-09-17 10:00 UTC, AivarIUsupov commented
> @AivarIUsupov Please add some tests for this case.
> Moreover, add this ticket to the NEWS.md-file.

I have made changes, so you can check them. 
Thank you for being attentive.

2021-09-17 13:57 UTC, VRohach approved these changes

2021-09-17 14:39 UTC, merged