MODSOURCE-459 Delete authority record
folio-org/mod-source-record-storage pull request #436
Opened 2022-02-23 13:46 UTC by Igor-Gorchakov

## Purpose
_Describe the purpose of the pull request. Include background information if necessary._

## Approach
_How does this change fulfill the purpose?_

#### TODOS and Open Questions
- [ ] Use GitHub checklists. When solved, check the box and explain the answer.

## Learning
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._

2022-03-01 09:36 UTC, ALiemeshka approved these changes

2022-03-01 12:42 UTC, viacheslavkol approved these changes

2022-03-02 12:00 UTC, RuslanLavrov commented on mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
> +      .compose(ar -> executor.execute(dsl -> purgeDeletedRecordsQuery))
hi @Igor-Gorchakov, I propose to perform records' deletion operations in transaction

2022-03-02 16:03 UTC, RuslanLavrov approved these changes

2022-03-09 11:08 UTC, psmagin requested changes
Please review once again approach suggest by SA.

2022-03-09 11:08 UTC, psmagin commented on mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDao.java
> +  Future<Void> cleanRecords(String tenantId);
It's needed to keep soft-deleted records for some time. In the approach described by SA, he suggests removing records that are older than 7 days. Also, he suggests limiting the maximum amount of records deleted for example by 500 records in a time.

2022-03-11 11:22 UTC, merged