Modsource 477
folio-org/mod-source-record-storage pull request #446
Opened 2022-03-23 20:20 UTC by Igor-Gorchakov

## Purpose
_Describe the purpose of the pull request. Include background information if necessary._

## Approach
_How does this change fulfill the purpose?_

#### TODOS and Open Questions
- [ ] Use GitHub checklists. When solved, check the box and explain the answer.

## Learning
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._

2022-03-25 09:59 UTC, psmagin requested changes

2022-03-25 09:59 UTC, psmagin commented on mod-source-record-storage-server/src/main/java/org/folio/services/cleanup/RecordCleanupService.java
> +    TenantUtil.getModuleTenants(vertx)
I think it will be useful to have some info message on the method start to show that cleanup job is started.

2022-03-25 09:59 UTC, psmagin commented on mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractDeleteEventHandler.java
>      var record = Json.decodeValue(payload.getContext().get(getRecordKey()), Record.class);
Please add info message there also.

2022-03-28 07:59 UTC, psmagin approved these changes

2022-03-28 10:12 UTC, RuslanLavrov approved these changes

2022-03-28 11:13 UTC, merged