MODSOURCE-567 Link update report: send event if update failed
folio-org/mod-source-record-storage pull request #512
Opened 2023-01-18 12:17 UTC by Shans-Kaluhin

2023-01-18 12:22 UTC, hasanepam approved these changes

2023-01-18 12:38 UTC, Shans-Kaluhin commented
This PR waits for merging this PR's:
`ramls`: https://github.com/folio-org/data-import-raml-storage/pull/271
`folio-kafka-wrapper`: https://github.com/folio-org/folio-kafka-wrapper/pull/35

2023-01-24 10:24 UTC, hasanepam approved these changes

2023-01-24 10:47 UTC, viacheslavkol approved these changes

2023-01-24 10:47 UTC, viacheslavkol commented on mod-source-record-storage-server/src/main/java/org/folio/consumers/AuthorityLinkChunkKafkaHandler.java
> -    var topicName = createTopicNameNoNamespace(SRS_BIB_UPDATE_TOPIC, marcBibUpdate.getTenant(), kafkaConfig);
This method could be also removed from utils

2023-01-24 10:47 UTC, viacheslavkol commented on mod-source-record-storage-server/src/test/java/org/folio/services/AuthorityLinkChunkKafkaHandlerTest.java
> +  private static final String KAFKA_KAFKA_SRS_BIB_PRODUCER_TOPIC = getTopicName(MARC_BIB);
Naming trouble

2023-01-24 11:55 UTC, psmagin requested changes
I don't think that we should send success events from srs. It's like a completion event for the whole update, and it can be completed fully only in inventory.

2023-01-25 10:23 UTC, merged